name: kaisa-tier01
services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - '127.0.0.1:5678:5678'
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    ports:
      - '127.0.0.1:2368:2368'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
